
package client.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T15:21:45.497+01:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "Exception", targetNamespace = "http://services/")
public class Exception_Exception extends java.lang.Exception {
    
    private client.stub.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, client.stub.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, client.stub.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public client.stub.Exception getFaultInfo() {
        return this.exception;
    }
}
