package client.stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T15:21:45.523+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "Security", 
                  wsdlLocation = "file:./src/main/resources/warehouse.wsdl",
                  targetNamespace = "http://services/") 
public class Security extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://services/", "Security");
    public final static QName WarehouseServicePort = new QName("http://services/", "WarehouseServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:./src/main/resources/warehouse.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(Security.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:./src/main/resources/warehouse.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public Security(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public Security(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Security() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns WarehouseService
     */
    @WebEndpoint(name = "WarehouseServicePort")
    public WarehouseService getWarehouseServicePort() {
        return super.getPort(WarehouseServicePort, WarehouseService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WarehouseService
     */
    @WebEndpoint(name = "WarehouseServicePort")
    public WarehouseService getWarehouseServicePort(WebServiceFeature... features) {
        return super.getPort(WarehouseServicePort, WarehouseService.class, features);
    }

}
