
package client.stub;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-10-28T15:21:45.237+01:00
 * Generated source version: 2.5.1
 * 
 */
public final class WarehouseService_WarehouseServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://services/", "Security");

    private WarehouseService_WarehouseServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = Security.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        Security ss = new Security(wsdlURL, SERVICE_NAME);
        WarehouseService port = ss.getWarehouseServicePort();  
        
        {
        System.out.println("Invoking addOrder...");
        client.stub.Order _addOrder_order = null;
        java.lang.String _addOrder__return = port.addOrder(_addOrder_order);
        System.out.println("addOrder.result=" + _addOrder__return);


        }
        {
        System.out.println("Invoking getAllNearlyOutOfStockGoods...");
        java.lang.String _getAllNearlyOutOfStockGoods__return = port.getAllNearlyOutOfStockGoods();
        System.out.println("getAllNearlyOutOfStockGoods.result=" + _getAllNearlyOutOfStockGoods__return);


        }
        {
        System.out.println("Invoking printListedWarehouseSchedule...");
        java.util.List<client.stub.Warehouse> _printListedWarehouseSchedule_warehouseList = null;
        java.lang.String _printListedWarehouseSchedule__return = port.printListedWarehouseSchedule(_printListedWarehouseSchedule_warehouseList);
        System.out.println("printListedWarehouseSchedule.result=" + _printListedWarehouseSchedule__return);


        }
        {
        System.out.println("Invoking getGoodsLocation...");
        java.lang.String _getGoodsLocation_goodsReference = "";
        java.util.List<client.stub.Warehouse> _getGoodsLocation__return = port.getGoodsLocation(_getGoodsLocation_goodsReference);
        System.out.println("getGoodsLocation.result=" + _getGoodsLocation__return);


        }
        {
        System.out.println("Invoking printSpecificWarehouseSchedule...");
        client.stub.Warehouse _printSpecificWarehouseSchedule_warehouse = null;
        java.lang.String _printSpecificWarehouseSchedule__return = port.printSpecificWarehouseSchedule(_printSpecificWarehouseSchedule_warehouse);
        System.out.println("printSpecificWarehouseSchedule.result=" + _printSpecificWarehouseSchedule__return);


        }
        {
        System.out.println("Invoking getGoodsQuantity...");
        java.lang.String _getGoodsQuantity_goodsReference = "";
        int _getGoodsQuantity__return = port.getGoodsQuantity(_getGoodsQuantity_goodsReference);
        System.out.println("getGoodsQuantity.result=" + _getGoodsQuantity__return);


        }
        {
        System.out.println("Invoking getSpecificWarehouseGoodsQuantity...");
        java.lang.String _getSpecificWarehouseGoodsQuantity_goodsReference = "";
        client.stub.Warehouse _getSpecificWarehouseGoodsQuantity_warehouse = null;
        int _getSpecificWarehouseGoodsQuantity__return = port.getSpecificWarehouseGoodsQuantity(_getSpecificWarehouseGoodsQuantity_goodsReference, _getSpecificWarehouseGoodsQuantity_warehouse);
        System.out.println("getSpecificWarehouseGoodsQuantity.result=" + _getSpecificWarehouseGoodsQuantity__return);


        }
        {
        System.out.println("Invoking getSpecificWarehouseNearlyOutOfStockGoods...");
        client.stub.Warehouse _getSpecificWarehouseNearlyOutOfStockGoods_warehouse = null;
        java.lang.String _getSpecificWarehouseNearlyOutOfStockGoods__return = port.getSpecificWarehouseNearlyOutOfStockGoods(_getSpecificWarehouseNearlyOutOfStockGoods_warehouse);
        System.out.println("getSpecificWarehouseNearlyOutOfStockGoods.result=" + _getSpecificWarehouseNearlyOutOfStockGoods__return);


        }
        {
        System.out.println("Invoking printGeneralSchedule...");
        java.lang.String _printGeneralSchedule__return = port.printGeneralSchedule();
        System.out.println("printGeneralSchedule.result=" + _printGeneralSchedule__return);


        }
        {
        System.out.println("Invoking addDeliverie...");
        client.stub.Deliverie _addDeliverie_deliverie = null;
        java.lang.String _addDeliverie__return = port.addDeliverie(_addDeliverie_deliverie);
        System.out.println("addDeliverie.result=" + _addDeliverie__return);


        }
        {
        System.out.println("Invoking addGoods...");
        java.util.List<client.stub.Goods> _addGoods_addedGoodsList = null;
        client.stub.Warehouse _addGoods_providedWarehouse = null;
        java.lang.String _addGoods__return = port.addGoods(_addGoods_addedGoodsList, _addGoods_providedWarehouse);
        System.out.println("addGoods.result=" + _addGoods__return);


        }
        {
        System.out.println("Invoking removeGoods...");
        java.util.List<client.stub.Goods> _removeGoods_removedGoodsList = null;
        client.stub.Warehouse _removeGoods_provisionningWarehouse = null;
        try {
            java.lang.String _removeGoods__return = port.removeGoods(_removeGoods_removedGoodsList, _removeGoods_provisionningWarehouse);
            System.out.println("removeGoods.result=" + _removeGoods__return);

        } catch (Exception_Exception e) { 
            System.out.println("Expected exception: Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getListedWarehouseNearlyOutOfStockGoods...");
        java.util.List<client.stub.Warehouse> _getListedWarehouseNearlyOutOfStockGoods_warehouseList = null;
        java.lang.String _getListedWarehouseNearlyOutOfStockGoods__return = port.getListedWarehouseNearlyOutOfStockGoods(_getListedWarehouseNearlyOutOfStockGoods_warehouseList);
        System.out.println("getListedWarehouseNearlyOutOfStockGoods.result=" + _getListedWarehouseNearlyOutOfStockGoods__return);


        }

        System.exit(0);
    }

}
