package transport.proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-23T19:40:07.207+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "DeliveryNetworkServiceService", 
                  wsdlLocation = "file:/home/cgallesi/MuleStudio/workspace/soa/lab2/src/main/resources/transport2.wsdl",
                  targetNamespace = "http://Transporteur2/") 
public class DeliveryNetworkServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://Transporteur2/", "DeliveryNetworkServiceService");
    public final static QName DeliveryNetworkPort = new QName("http://Transporteur2/", "DeliveryNetworkPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/cgallesi/MuleStudio/workspace/soa/lab2/src/main/resources/transport2.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeliveryNetworkServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/home/cgallesi/MuleStudio/workspace/soa/lab2/src/main/resources/transport2.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeliveryNetworkServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeliveryNetworkServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeliveryNetworkServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DeliveryNetwork
     */
    @WebEndpoint(name = "DeliveryNetworkPort")
    public DeliveryNetwork getDeliveryNetworkPort() {
        return super.getPort(DeliveryNetworkPort, DeliveryNetwork.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeliveryNetwork
     */
    @WebEndpoint(name = "DeliveryNetworkPort")
    public DeliveryNetwork getDeliveryNetworkPort(WebServiceFeature... features) {
        return super.getPort(DeliveryNetworkPort, DeliveryNetwork.class, features);
    }

}
