package transport.proxy;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-23T19:40:07.172+01:00
 * Generated source version: 2.5.1
 * 
 */
@WebService(targetNamespace = "http://Transporteur2/", name = "DeliveryNetwork")
@XmlSeeAlso({ObjectFactory.class})
public interface DeliveryNetwork {

    @WebResult(name = "quote_response", targetNamespace = "")
    @RequestWrapper(localName = "quote", targetNamespace = "http://Transporteur2/", className = "transport.proxy.Quote")
    @WebMethod
    @ResponseWrapper(localName = "quoteResponse", targetNamespace = "http://Transporteur2/", className = "transport.proxy.QuoteResponse")
    public transport.proxy.DeliveryPersonalResponse quote(
        @WebParam(name = "quote_request", targetNamespace = "")
        transport.proxy.DeliveryPersonalRequest quoteRequest
    ) throws DeliveryFault_Exception;

    @WebResult(name = "delivery_response", targetNamespace = "")
    @RequestWrapper(localName = "delivery", targetNamespace = "http://Transporteur2/", className = "transport.proxy.Delivery")
    @WebMethod
    @ResponseWrapper(localName = "deliveryResponse", targetNamespace = "http://Transporteur2/", className = "transport.proxy.DeliveryResponse")
    public transport.proxy.DeliveryPersonalResponse delivery(
        @WebParam(name = "delivery_request", targetNamespace = "")
        transport.proxy.DeliveryPersonalRequest deliveryRequest
    ) throws DeliveryFault_Exception;

    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    @WebResult(name = "trackResponse", targetNamespace = "http://Transporteur2/", partName = "parameters")
    @WebMethod
    public TrackResponse track(
        @WebParam(partName = "parameters", name = "track", targetNamespace = "http://Transporteur2/")
        Track parameters,
        @WebParam(partName = "number", name = "number", targetNamespace = "http://Transporteur2/", header = true)
        java.lang.String number
    ) throws TrackFault_Exception;
}
