
package transport.proxy;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.5.1
 * 2013-11-23T19:40:07.133+01:00
 * Generated source version: 2.5.1
 */

@WebFault(name = "TrackFault", targetNamespace = "http://Transporteur2/")
public class TrackFault_Exception extends Exception {
    
    private transport.proxy.TrackFault trackFault;

    public TrackFault_Exception() {
        super();
    }
    
    public TrackFault_Exception(String message) {
        super(message);
    }
    
    public TrackFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public TrackFault_Exception(String message, transport.proxy.TrackFault trackFault) {
        super(message);
        this.trackFault = trackFault;
    }

    public TrackFault_Exception(String message, transport.proxy.TrackFault trackFault, Throwable cause) {
        super(message, cause);
        this.trackFault = trackFault;
    }

    public transport.proxy.TrackFault getFaultInfo() {
        return this.trackFault;
    }
}
